version: '3.5'

services:
  dev-mysql:
    image: bitnami/mysql:latest
    container_name: necolo007-mysql-ctn
    ports:
      - "13306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=dev
      - MYSQL_CHARSET=utf8mb4